openapi: 3.0.1
info:
  title: System Info and Command Runner Plugin
  description: A plugin that allows users to run command line programs after obtaining the system information.
  version: 'v1'
servers:
  - url: http://localhost:5004
paths:
  /system/os-version:
    get:
      operationId: getOSVersion
      summary: Get the OS version
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OSVersionResponse'
  /system/local-time:
    get:
      operationId: getLocalTime
      summary: Get the local time
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LocalTimeResponse'
  /system/current-folder:
    get:
      operationId: getCurrentFolder
      summary: Get the current folder
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CurrentFolderResponse'
  /system/command:
    post:
      operationId: runCommand
      summary: Run a command
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RunCommandRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RunCommandResponse'
components:
  schemas:
    OSVersionResponse:
      type: object
      properties:
        os_version:
          type: string
          description: The OS version.
    LocalTimeResponse:
      type: object
      properties:
        local_time:
          type: string
          description: The local time.
    CurrentFolderResponse:
      type: object
      properties:
        current_folder:
          type: string
          description: The current folder.
    RunCommandRequest:
      type: object
      required:
      - command
      properties:
        command:
          type: string
          description: The command to run.
          required: true
    RunCommandResponse:
      type: object
      properties:
        output:
          type: string
          description: The output of the command.
